The purpose of the application is to examine the possibility of coordinating bids in the tender.<br>
The application is part of our final project in undergraduate studies in Industrial Engineering and Management at SCE College in Be'er Sheva under the supervision of Dr. Yitzhak Minchuk.

#### What is Bid?

**Bid Definition** 
<br />
An offer made by an individual or corporation to purchase an asset. Buyers commonly make bids at auctions and in various markets, such as the stock market. Bids may also be made by companies that compete for project contracts. When a buyer makes a bid, they stipulate how much they're willing to pay for the asset along with how much they are willing to purchase.

### Procurement Bids
<br />
A procurement bid is a process for approaching a competitive market to buy goods or services.
A procurement bid or a reverse bid is when a number of sellers compete with one another to win the business of one buyer.

#### Methods We Use
**Cluster Analysis** 
<br />
Cluster analysis or clustering is the task of grouping a set of objects in such a way that objects in the same group (called a cluster) are more similar (in some sense) to each other than to those in other groups (clusters).

**Kolmogorov–Smirnov test** 
<br />
In statistics, the Kolmogorov–Smirnov test is a nonparametric test of the equality of continuous , one-dimensional probability distributions that can be used to compare a sample with a reference probability distribution (one-sample K–S test), or to compare two samples (two-sample K–S test). In essence, the test answers the question "What is the probability that this collection of samples could have been drawn from that probability distribution?" or, in the second case, "What is the probability that these two sets of samples were drawn from the same (but unknown) probability distribution?".

**T test** 
<br />
A t-test is a type of inferential statistic used to determine if there is a significant difference between the means of two groups, which may be related in certain features. A t-test is used as a hypothesis testing tool, which allows testing of an assumption applicable to a population. 

**Skewness** 
<br />
Skewness is a measure of the asymmetry of the probability distribution of a real-valued random variable about its mean. The skewness value can be positive, zero, negative, or undefined. 

**F Test**
<br />
It is a catch-all term for any test that uses the F-distribution. In most cases, when people talk about the F-Test, what they are actually talking about is The F-Test to Compare Two Variances. However, the f-statistic is used in a variety of tests including regression analysis, the Chow test and the Scheffe Test (a post-hoc ANOVA test).

#### References
A Survey of Auction Theory. [Chapter one](http://assets.press.princeton.edu/chapters/s7728.pdf).
Detection of collusion in government procurement auctions. [Detection of collusion in bids](https://www.sciencedirect.com/science/article/abs/pii/S1478409211000161).
What Really Matters in Auction Design. [Paul Klemperer](https://www.aeaweb.org/articles?id=10.1257/0895330027166).